---
apiVersion: v1
kind: Pod 
metadata:
  name: tomcat-pod
  labels: 
    name: myapp
spec:
  containers:
   - name: mytomcat
     image: tomee
     ports:
      - containerPort: 8080
        hostPort: 9090
...