---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: webser
spec:
  containers:
    - name: myhttpd
      image: httpd
      ports: 
        - containerPort: 80
          hostPort: 8080
...

