---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: db
    author: naribabu
spec:
  containers:
    - name: mydb
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: nari9
        - name: POSTGRES_USER
          value: nariuser
        - name: POSTGRES_DB
          value: mydb
...