---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    name: ci-cd
    author: narihome
spec:
  containers:
    - name: myjrnkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090
...